name: .dgtrader-venv
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=25.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.34.0
  - jedi=0.19.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=20.1.1
  - libedit=3.1.20250104
  - libffi=3.4.2
  - liblzma=5.6.4
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - narwhals=1.32.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - plotly=6.0.1
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python_abi=3.10
  - pyzmq=26.3.0
  - readline=8.2
  - referencing=0.36.2
  - rpds-py=0.24.0
  - setuptools=75.8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.4
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - quantconnect-lean==0.1.0
      - quantconnect-stubs==17034
      - tzdata==2025.2
prefix: .dgtrader-venv
